### ISSUE TITLE
Discrepancy of local daily net income and EiB Daily revenue

### ISSUE THREAD

**Issue by jenshorn** [faanskit/ha-checkwatt#57]
I noticed that there is a discrepancy the local `daily net income` sensor and EiB portal `Daily revenue`. In my current case the local sensor state _15.41_ and the EiB Daily revenue states _17.31_. Is that to be expected with the APIs being used? Am I missing something or perhaps looking at the wrong thing? The local sensor is being updated continuously as far as I can see.

**Comment by flopp999** [comment]
What version of CheckWatt integration do you use?

**Comment by faanskit** [comment]
This is a known issue coming from a recent change in EIB. v0.2.0 will fix this, and can be tested already now if you enable Beta in Hacs and upgrade to v0.2.0-RC.4.

The background is that CheckWatt changed the way they calculate and compensate and upgraded the EIB portal. The ha-integration up until v.0.2.0 still use the old endpoints and the old ways to calculate.

**Comment by faanskit** [comment]
Please upgrade to:
https://github.com/faanskit/ha-checkwatt/releases/tag/v0.2.0-RC.4

Kindly report back if the issue remains. The issue will remain open until release v0.2.0 currently under test

**Comment by jenshorn** [comment]
> What version of CheckWatt integration do you use?

Sorry, of course I've should've mentioned that initially: `v0.1.6`.

**Comment by jenshorn** [comment]
`v0.2.0-RC.4` solves this, now the sensor matches EiB GUI ✨👍

**Comment by faanskit** [comment]
Solved with v0.2.0, now released
