### ISSUE TITLE
Failed to authorize

### ISSUE THREAD

**Issue by linusst** [faanskit/ha-checkwatt#69]
The integration can not login to energyinbalance.

Message is "Failed to authorize" and in the log it says:

This error originated from a custom integration.

Logger: pycheckwatt
Source: custom_components/checkwatt/config_flow.py:42
integration: CheckWatt (documentation, issues)
First occurred: 21:03:26 (1 occurrences)
Last logged: 21:04:19

CheckWatt has requested to back down by enabling the kill-switch

I have even tryed to reset the password to one without special signs.

**Comment by faanskit** [comment]
Hi, this is a deliberate agreement with developers at checkwatt.

When the file ha-killswitch.txt assumes the value 1, CheckWatt want the ha-checkwatt to stop "hammering" on the API.
I'll check with the developers if this was on purpose.

You can always try to see the status of the killswitch on this link:[link](https://checkwatt.se/ha-killswitch.txt)

Currently it is set to 1, so the integration is therefore blocked. Good to see it in production.

**Comment by linusst** [comment]
Thanks for the quick reply.

**Comment by faanskit** [comment]
Checkwatt has confirmed that they engaged the killswitch to preserve their servers which were running hot.

They appreciate that it exist and the cooperation around it.
They intend the disengage the killswitch as soon as they have stabilized, which would be any-day.

So, this is not a bug but a feature that worked as designed and is now proven in battle.
