### ISSUE TITLE
Unit displayed before the number, instead of after

### ISSUE THREAD

**Issue by str2der** [faanskit/ha-checkwatt#71]
The sensors units (SEK, for instance) is presented before instead of after the numbers. All other sensors in Home assistant present the unit after the number.

<img width="260" alt="Skärmbild 2024-04-22 142256" src="https://github.com/faanskit/ha-checkwatt/assets/33718692/4469be80-c82a-41b9-a6ea-7234d83ad0b0">

**Comment by faanskit** [comment]
This is unlikely a bug of this integration, but rather a Home Assistant locale configuration issue.
The first referenced sensor is defined like this, all according to the playbook of Home Assistant developments:

```python
    "annual": SensorEntityDescription(
        key="annual_yield",
        name="CheckWatt Annual Yield",
        icon="mdi:account-cash-outline",
        device_class=SensorDeviceClass.MONETARY,
        native_unit_of_measurement="SEK",
        state_class=SensorStateClass.TOTAL,
        translation_key="annual_yield_sensor",
    ),
```

The second referenced sensor is not part of ha-checkwatt, but instead likely something built using a template.
I do not know how that sensor is typed as it is locally developed.

When using Swedish locale settings in HA, it looks like this:
![image](https://github.com/faanskit/ha-checkwatt/assets/10439868/f8a50494-6617-49eb-b71b-ce5c16372080)

I.e. unit (kr) is post-fix, not pre-fixed.

May I request you to check and revise your Home Assistant locale configurations and report back.

**Comment by faanskit** [comment]
...oh...one more thing...

Take note that there are two places where you define locale in Home Assistant.
You have both user-, and system locale settings.

Likely ha-checkwatt use user locale, and the template sensor use system locale.
