### ISSUE TITLE
Custom component not found in add integration screen

### ISSUE THREAD

**Issue by TheUnseenBug** [faanskit/ha-checkwatt#77]
Hello,
I am using a homeassistant green and have git cloned the repository under the config folder in a custom_components folder and I can see all the data using the terminal however when going to the add integration popup Checkwatt is not found. I have tried restarting the homeassistant and hard refreshing and using a new browser so should not be a cookies issue atleast.

**Comment by faanskit** [comment]
Please give some more details, impossible to support with this little information.
Can you please give the outline of the directory `custom_components`, i.e. like this:

```
# ~ cd ~/config/custom_components
# pwd                          
/root/config/custom_components
# ls -la                       
total 32
drwxr-xr-x    8 root     root          4096 Jun 23 08:25 .
drwxr-xr-x   10 root     root          4096 Jul 11 11:33 ..
drwxr-xr-x    4 root     root          4096 Jun 23 08:25 checkwatt
drwxr-xr-x    4 root     root          4096 May 20 12:45 easee
drwxr-xr-x   10 root     root          4096 Mar 28 11:44 hacs
drwxr-xr-x    4 root     root          4096 Mar 28 14:12 nordpool
drwxr-xr-x    4 root     root          4096 May 20 12:35 openai_tts
drwxr-xr-x    4 root     root          4096 Mar 28 11:48 plejd
```

**Comment by faanskit** [comment]
Likely not a bug, follow discussion #76
