### ISSUE TITLE
Logged out

### ISSUE THREAD

**Issue by hedlung** [faanskit/ha-checkwatt#78]
@faanskit 
Suddenly I got a prompt that I have Unavailable entries in HA. I check and find that all of the Checkwatt integration is not working.
I remove the integration and upon adding it prompt med for username and pwd, but cannot authorize. I have tried on EIB and even changed pwd but no luck. 
In the HA core log file I find this entry:

**
This error originated from a custom integration.

Logger: pycheckwatt
Source: custom_components/checkwatt/config_flow.py:42
integration: CheckWatt (documentation, issues)
First occurred: 16:24:15 (2 occurrences)
Last logged: 16:29:19

CheckWatt has requested to back down by enabling the kill-switch
 **

Have CW changed their login API?

**Comment by faanskit** [comment]
Not a bug, integration honors a key switch. When enabled by Checkwatt, integration stops.
When checkwatt disable Killswitch it'll resume again.
